_base_ = '../../../mmdet/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py'

model = dict(
    roi_head=dict(
        bbox_head=dict(
            num_classes=113
        )
    )
)

dataset_type = 'CocoDataset'
data_root = '../data/ai_products/'

classes = ("3+2-2",
"3jia2",
"aerbeisi",
"anmuxi",
"aoliao",
"asamu",
"baicha",
"baishikele",
"baishikele-2",
"baokuangli",
"binghongcha",
"bingqilinniunai",
"bingtangxueli",
"buding",
"chacui",
"chapai",
"chapai2",
"damaicha",
"daofandian1",
"daofandian2",
"daofandian3",
"daofandian4",
"dongpeng",
"dongpeng-b",
"fenda",
"gudasao",
"guolicheng",
"guolicheng2",
"haitai",
"haochidian",
"haoliyou",
"heweidao",
"heweidao2",
"heweidao3",
"hongniu",
"hongniu2",
"hongshaoniurou",
"jianjiao",
"jianlibao",
"jindian",
"kafei",
"kaomo_gali",
"kaomo_jiaoyan",
"kaomo_shaokao",
"kaomo_xiangcon",
"kebike",
"kele",
"kele-b",
"kele-b-2",
"laotansuancai",
"liaomian",
"libaojian",
"lingdukele",
"lingdukele-b",
"liziyuan",
"lujiaoxiang",
"lujikafei",
"luxiangniurou",
"maidong",
"mangguoxiaolao",
"meiniye",
"mengniu",
"mengniuzaocan",
"moliqingcha",
"nfc",
"niudufen",
"niunai",
"nongfushanquan",
"qingdaowangzi-1",
"qingdaowangzi-2",
"qinningshui",
"quchenshixiangcao",
"rancha-1",
"rancha-2",
"rousongbing",
"rusuanjunqishui",
"suanlafen",
"suanlaniurou",
"taipingshuda",
"tangdaren",
"tangdaren2",
"tangdaren3",
"ufo",
"ufo2",
"wanglaoji",
"wanglaoji-c",
"wangzainiunai",
"weic",
"weitanai",
"weitanai2",
"weitanaiditang",
"weitaningmeng",
"weitaningmeng-bottle",
"weiweidounai",
"wuhounaicha",
"wulongcha",
"xianglaniurou",
"xianguolao",
"xianxiayuban",
"xuebi",
"xuebi-b",
"xuebi2",
"yezhi",
"yibao",
"yida",
"yingyangkuaixian",
"yitengyuan",
"youlemei",
"yousuanru",
"youyanggudong",
"yuanqishui",
"zaocanmofang",
"zihaiguo",
)

data = dict(
    train=dict(
        type=dataset_type,
        classes=classes,
        ann_file=data_root + 'train.json',
        img_prefix=data_root + 'JPEGImages/'
    ),
    val=dict(
        type=dataset_type,
        classes=classes,
        ann_file=data_root + 'val.json',
        img_prefix=data_root + 'JPEGImages/'
    ),
    test=dict(
        type=dataset_type,
        classes=classes,
        ann_file=data_root + 'test.json',
        img_prefix=data_root + 'JPEGImages/'
    )
)

load_from = '../checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth'
